name: seg_d2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.2
  get: ^4.6.5
  firebase_core:
  firebase_auth:
  pinput: ^2.2.31
  video_player: ^2.7.0
  chewie: ^1.7.0
  firebase_database:
  image_picker:
#  better_player:
  firebase_storage: ^11.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.1.0

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/loginimg2.jpg
    - images/blackgrad.webp
    - images/phone.jpg
    - images/signup.jpg


